"""Loading of reference data, ingest records, and append-only run/override storage.

CRM and plan values live here and are never handed to the LLM. `reference_for()`
is the only way a check reaches them, and it is called *after* extraction.
"""

from __future__ import annotations

import hashlib
import json
import threading
import uuid
from datetime import datetime, timezone
from pathlib import Path

from .config import DATA_DIR, ROOT, RUNS_DIR

# Recordings pushed by the dialler, and the transcripts ASR produced from them.
AUDIO_DIR = RUNS_DIR / "audio"
ASR_DIR = RUNS_DIR / "transcripts"
AUDIO_TYPES = {".wav": "audio/wav", ".mp3": "audio/mpeg", ".m4a": "audio/mp4",
               ".ogg": "audio/ogg", ".flac": "audio/flac", ".webm": "audio/webm"}
from .textutil import redact_long_digits

_LOCK = threading.Lock()


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def _read_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def _dig(root: dict, path: str | None):
    """Resolve a dotted path like 'plan.promo_price_cents'."""
    value = root
    for part in (path or "").split("."):
        if not isinstance(value, dict):
            return None
        value = value.get(part)
    return value


class Store:
    def __init__(self) -> None:
        self.leads_doc = _read_json(DATA_DIR / "leads.json")
        synth = DATA_DIR / "synth" / "leads.json"
        if synth.exists():
            # Generated by tools/synth_calls.py. Kept in their own file so the brief's
            # fixtures stay untouched; merged here so the whole app sees one lead list.
            self.leads_doc = {**self.leads_doc,
                              "leads": self.leads_doc["leads"] + _read_json(synth)["leads"]}
        self.plans_doc = _read_json(DATA_DIR / "plans.json")
        self.checks_doc = _read_json(DATA_DIR / "checks.json")
        self.leads = {lead["lead_id"]: lead for lead in self.leads_doc["leads"]}
        self.plans = {plan["plan_id"]: plan for plan in self.plans_doc["plans"]}
        # The top-level checklist is the default pack (Retailer 1 energy). Extra packs
        # (e.g. NBN-QA) apply only to leads that name them with "check_pack".
        self.checks = self.checks_doc["checks"]
        self.packs = {pack["pack_id"]: pack for pack in self.checks_doc.get("extra_packs", [])}
        self.ingests: dict[str, dict] = {}
        self.runs: dict[str, dict] = {}
        self.run_ids_by_lead: dict[str, list[str]] = {}
        RUNS_DIR.mkdir(parents=True, exist_ok=True)
        AUDIO_DIR.mkdir(parents=True, exist_ok=True)
        ASR_DIR.mkdir(parents=True, exist_ok=True)

    # ---------------------------------------------------------------- reference

    def lead(self, lead_id: str) -> dict:
        try:
            return self.leads[lead_id]
        except KeyError:
            raise KeyError(f"unknown lead_id {lead_id!r}") from None

    def pack_for(self, lead_id: str) -> dict:
        """The checklist a lead is scored against: its named pack, else the default."""
        name = self.lead(lead_id).get("check_pack")
        if not name:
            return self.checks_doc
        try:
            return self.packs[name]
        except KeyError:
            raise KeyError(f"lead {lead_id} names unknown check pack {name!r}") from None

    def checks_for(self, lead_id: str) -> list[dict]:
        return self.pack_for(lead_id)["checks"]

    def plan_for(self, lead_id: str) -> dict:
        lead = self.lead(lead_id)
        if isinstance(lead.get("plan"), dict):
            return lead["plan"]  # plan carried on the lead itself (no catalogue entry)
        try:
            return self.plans[lead["plan_id"]]
        except KeyError:
            raise KeyError(f"lead {lead_id} references unknown plan {lead['plan_id']!r}") from None

    def reference_for(self, check: dict, lead_id: str):
        """Resolve the CRM / plan value a Type B check compares against.

        Returns (value, label, source). Called only after the LLM has finished.
        """
        ref = check["script_or_rule"].get("reference") or {}
        source, path = ref.get("source"), ref.get("path")
        if source == "crm":
            root = self.lead(lead_id)["crm"]
        elif source == "plan":
            root = self.plan_for(lead_id)
        elif source == "lead":
            root = self.lead(lead_id)
        else:
            raise ValueError(f"check {check['check_id']}: unsupported reference source {source!r}")
        # A list of paths resolves to {path: value}, for comparators that weigh
        # several facts at once (a fee, whether it applies, the order total).
        if isinstance(path, list):
            value = {p: _dig(root, p) for p in path}
            label = ref.get("label", ", ".join(path))
        else:
            value, label = _dig(root, path), ref.get("label", path)
        return value, label, source

    def secret_reference_values(self, lead_id: str) -> list[str]:
        """Every CRM/plan value the LLM must never be shown. Used by the leak guard."""
        out: list[str] = []
        crm = self.lead(lead_id).get("crm", {})
        plan = self.plan_for(lead_id)
        extra = []
        lead = self.lead(lead_id)
        if isinstance(lead.get("plan"), dict):
            # Inline plans: every numeric fact is a reference value, in cents and dollars.
            for key, value in list(plan.items()) + [(k, lead.get(k)) for k in ("tmc_cents", "new_development_fee_cents")]:
                if isinstance(value, (int, float)) and not isinstance(value, bool):
                    extra.append(value)
                    if key.endswith("_cents"):
                        extra.append(f"{value / 100:.2f}")
        for value in list(crm.values()) + [
            plan.get("peak_rate_cents"),
            plan.get("daily_supply_cents"),
            plan.get("solar_fit_cents"),
        ] + extra:
            if value is None or isinstance(value, bool):
                continue
            text = str(value).strip()
            if len(text) >= 3:
                out.append(text)
        return out

    # ------------------------------------------------------------------- ingest

    def asr_transcript_path(self, lead_id: str) -> Path:
        return ASR_DIR / f"{lead_id}.json"

    def ingest(self, lead_id: str, redact_digit_run: int = 13, source: str = "auto") -> dict:
        """Attach a transcript for a lead. No file picker in the happy path.

        source="auto" prefers the transcript ASR produced from a dialler recording,
        because that is the real call; the local fixture is the stand-in until one
        arrives. "fixture" and "asr" force one or the other.
        """
        lead = self.lead(lead_id)
        asr_path = self.asr_transcript_path(lead_id)
        if source == "asr" or (source == "auto" and asr_path.exists()):
            path, kind = asr_path, "dialler_recording_asr"
        else:
            path, kind = ROOT / lead["transcript_path"], "local_fixture"
        if not path.exists():
            raise FileNotFoundError(f"transcript missing for lead {lead_id}: {path}")
        raw_bytes = path.read_bytes()
        doc = json.loads(raw_bytes.decode("utf-8"))

        if doc.get("lead_id") != lead_id:
            raise ValueError(
                f"transcript {path.name} declares lead_id {doc.get('lead_id')!r}, expected {lead_id!r}"
            )

        turns, redactions = [], int(doc.get("redactions_at_asr") or 0)
        for i, turn in enumerate(doc.get("turns", [])):
            text, masked = redact_long_digits(turn.get("text", ""), redact_digit_run)
            redactions += masked
            start = float(turn.get("start_sec", 0))
            turns.append(
                {
                    "idx": int(turn.get("idx", i)),
                    "speaker": turn.get("speaker", "unknown"),
                    "speaker_name": turn.get("speaker_name", turn.get("speaker", "unknown")),
                    "text": text,
                    "start_sec": start,
                    "end_sec": float(turn.get("end_sec", start)),
                    "asr_confidence": float(turn.get("asr_confidence", 1.0)),
                    "redacted": masked > 0,
                }
            )
        turns.sort(key=lambda t: (t["start_sec"], t["idx"]))

        record = {
            "ingest_id": f"ING-{lead_id}-{uuid.uuid4().hex[:8]}",
            "lead_id": lead_id,
            "source": kind,
            "transcript_path": (path.relative_to(ROOT) if path.is_relative_to(ROOT) else path).as_posix(),
            "transcript_sha256": hashlib.sha256(raw_bytes).hexdigest(),
            "call_id": doc.get("call_id"),
            "recorded_at": doc.get("recorded_at"),
            "audio_quality": doc.get("audio_quality", "unknown"),
            "audio_quality_note": doc.get("audio_quality_note"),
            "asr_engine": doc.get("asr_engine"),
            "speaker_mapping": doc.get("speaker_mapping"),
            "audio": doc.get("audio"),
            "duration_sec": float(doc.get("duration_sec") or (turns[-1]["end_sec"] if turns else 0)),
            "turn_count": len(turns),
            "redactions_applied": redactions,
            "redaction_rule": f"runs of {redact_digit_run}+ digits",
            "ingested_at": utcnow(),
            "turns": turns,
        }
        with _LOCK:
            self.ingests[record["ingest_id"]] = record
        return record

    # -------------------------------------------------------------------- audio

    def audio_for(self, lead_id: str) -> Path | None:
        """The recording for a lead: the dialler's upload if there is one, else a synthetic file."""
        for ext in AUDIO_TYPES:
            path = AUDIO_DIR / f"{lead_id}{ext}"
            if path.exists():
                return path
        declared = self.lead(lead_id).get("audio_path")
        if declared and (ROOT / declared).exists():
            return ROOT / declared
        return None

    def save_audio(self, lead_id: str, data: bytes, ext: str) -> Path:
        ext = ext if ext in AUDIO_TYPES else ".wav"
        with _LOCK:
            for old in AUDIO_DIR.glob(f"{lead_id}.*"):
                old.unlink()
            path = AUDIO_DIR / f"{lead_id}{ext}"
            path.write_bytes(data)
        return path

    def save_asr_transcript(self, lead_id: str, doc: dict) -> Path:
        path = self.asr_transcript_path(lead_id)
        with _LOCK:
            path.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
        return path

    def get_ingest(self, ingest_id: str) -> dict:
        try:
            return self.ingests[ingest_id]
        except KeyError:
            raise KeyError(f"unknown ingest_id {ingest_id!r}") from None

    # ---------------------------------------------------------------------- runs

    def new_run_id(self, lead_id: str) -> str:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S")
        return f"RUN-{lead_id}-{stamp}-{uuid.uuid4().hex[:4]}"

    def save_run(self, run: dict) -> dict:
        with _LOCK:
            self.runs[run["run_id"]] = run
            self.run_ids_by_lead.setdefault(run["lead_id"], [])
            if run["run_id"] not in self.run_ids_by_lead[run["lead_id"]]:
                self.run_ids_by_lead[run["lead_id"]].append(run["run_id"])
            path = RUNS_DIR / f"{run['run_id']}.json"
            path.write_text(json.dumps(run, indent=2, ensure_ascii=False), encoding="utf-8")
        return run

    def get_run(self, run_id: str) -> dict:
        with _LOCK:
            run = self.runs.get(run_id)
        if run is not None:
            return run
        path = RUNS_DIR / f"{run_id}.json"
        if path.exists():
            run = _read_json(path)
            with _LOCK:
                self.runs[run_id] = run
            return run
        raise KeyError(f"unknown run_id {run_id!r}")

    def latest_run_for(self, lead_id: str) -> dict | None:
        """Newest run for a lead, from this process or from disk (run ids sort by time)."""
        self.lead(lead_id)
        ids = list(self.run_ids_by_lead.get(lead_id) or [])
        ids += [p.stem for p in RUNS_DIR.glob(f"RUN-{lead_id}-*.json")]
        return self.get_run(max(ids)) if ids else None

    # ----------------------------------------------------------- override log

    def append_override(self, entry: dict) -> None:
        """Append-only. Overrides are added to history; nothing is ever rewritten."""
        with _LOCK:
            path = RUNS_DIR / "override_log.jsonl"
            with path.open("a", encoding="utf-8") as fh:
                fh.write(json.dumps(entry, ensure_ascii=False) + "\n")

    def read_override_log(self, limit: int = 200) -> list[dict]:
        path = RUNS_DIR / "override_log.jsonl"
        if not path.exists():
            return []
        rows = []
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                try:
                    rows.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
        return rows[-limit:]
